### ISSUE TITLE
error traceback in examples

### ISSUE THREAD

**Issue by ghost** [MPIIComputationalEpigenetics/DeepBlue-Manual#10]
I am pretty sure that is not supposed to be part of the tutorials:

![405](https://cloud.githubusercontent.com/assets/5285064/10620159/d11c3258-7779-11e5-9ada-a22069650ca6.jpg)

**Comment by felipealbrecht** [comment]
Thank , I will remove the tutorials links ASAP and convert them to 
examples style.

Peter Ebert wrote:

**Comment by felipealbrecht** [comment]
Fixes in the new tutorials.
